# Site settings
title: Mysteries-R-Us
tag_text: Do you have a mystery in need of solving?
description: Do you have an unsolved mystery in the Sydney area? We can solve it for you in most cases for no charge.

# Build settings
markdown: kramdown
sass:
  style: compressed
