# Site settings
title: Mystery Dog
tag_text: Need a mystery solved?
description: Do you have an unsolved mystery in the Sydney area? Mystery Dog can solve it for you in most cases for no charge.

# Build settings
markdown: kramdown
sass:
  style: compressed

# Google services
google_analytics: UA-91068857-1
